server:
  port: 8001
spring:
  application:
    name: apirouteservice
  redis:
      host: localhost
      password: pass123
      port: 6379
      database: 1
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    userservice:
      path: /user/**
      strPrefix: true
      url: http://localhost:9002/user
    orgservice:
      path: /orgin/**
      strPrefix: true
      url: http://localhost:9001/orgin